//------------------EXERCISE 1------------------
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

// Find the sum of all the multiples of 3 or 5 below 1000.

// const nums = [];
// sum = (t, n) => t + n;
// for (let i = 0; i < 1000; i++) {
// 	if (i % 3 === 0 || i % 5 === 0) {
// 		nums.push(i);
// 	}
// };
// console.log(nums.reduce(sum));

//------------------EXERCISE 2------------------
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// let sum = 0, a = 1, b = 2, temp;
// for (let b=2; b < 4000000; b+a){
// 	if(b % 2 === 0){
// 		sum += b;
// 	}
// 	temp = b, b += a, a=temp;
// };
// console.log(sum);